
name: Check GitHub Actions Quota

on:
  workflow_dispatch:  # 手动触发
  #schedule:
  #  - cron: '0 0 * * *'  # 每天UTC时间0点自动运行

jobs:
  check-quota:
    runs-on: ubuntu-latest
    steps:
      - name: Check API rate limit
        run: |
          # 获取当前账号的Actions配额信息
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/rate_limit")
          
          # 解析剩余分钟数
          remaining=$(echo "$response" | jq -r '.resources.actions.remaining')
          limit=$(echo "$response" | jq -r '.resources.actions.limit')
          reset_time=$(echo "$response" | jq -r '.resources.actions.reset')
          
          # 转换为北京时间并计算剩余百分比
          reset_readable=$(date -d @$reset_time +"%Y-%m-%d %H:%M:%S")
          percentage=$((remaining * 100 / limit))
          
          echo "剩余额度: $remaining/$limit 分钟 ($percentage%)"
          echo "重置时间: $reset_readable (UTC)"
          
          # 低于20%时警告
          if [ $percentage -lt 20 ]; then
            echo "::warning::GitHub Actions剩余额度不足20%!"
          fi
