name: Check GitHub Actions Quota (Personal Account)

on:
  workflow_dispatch:  # 手动触发
  #schedule:
  #  - cron: '0 0 * * *'  # 每天凌晨运行一次（可选）

jobs:
  check-quota:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get Actions Quota (Personal Account)
        id: quota
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
        run: |
          API_URL="https://api.github.com/users/${GITHUB_ACTOR}/settings/billing/actions"
          AUTH_HEADER="Authorization: Bearer $GITHUB_PAT"

          echo "Fetching Actions quota data from GitHub..."

          RESPONSE=$(curl -s -H "$AUTH_HEADER" -H "Accept: application/vnd.github+json" $API_URL)

          if [[ $? -ne 0 ]]; then
            echo "❌ Failed to fetch data from GitHub API."
            exit 1
          fi

          # 解析 JSON 数据
          included_minutes=$(echo "$RESPONSE" | jq -r '.included_minutes')
          total_minutes_used=$(echo "$RESPONSE" | jq -r '.total_minutes_used')
          total_paid_minutes_used=$(echo "$RESPONSE" | jq -r '.total_paid_minutes_used')
          total_minutes_allocated=$(echo "$RESPONSE" | jq -r '.total_minutes_allocated')

          # 将变量写入环境变量供后续步骤使用
          echo "included_minutes=$included_minutes" >> $GITHUB_ENV
          echo "total_minutes_used=$total_minutes_used" >> $GITHUB_ENV
          echo "total_paid_minutes_used=$total_paid_minutes_used" >> $GITHUB_ENV
          echo "total_minutes_allocated=$total_minutes_allocated" >> $GITHUB_ENV

      - name: Show Quota Info
        run: |
          remaining_minutes=$(( included_minutes - total_minutes_used ))
          echo "📊 GitHub Actions Monthly Quota Info"
          echo "--------------------------------------"
          echo "Included Free Minutes:       $included_minutes 分钟"
          echo "Total Minutes Used:          $total_minutes_used 分钟"
          echo "Total Paid Minutes Used:     $total_paid_minutes_used 分钟"
          echo "Total Minutes Allocated:     $total_minutes_allocated 分钟"
          echo "Remaining Free Minutes:      $remaining_minutes 分钟"
          echo "Remaining Free Hours:        $(( remaining_minutes / 60 )) 小时 $(( remaining_minutes % 60 )) 分钟"
          echo "--------------------------------------"

      - name: Warn if near quota limit
        if: env.remaining_minutes < 100
        run: |
          echo "⚠️ Warning: You have less than 100 free minutes left!"
