name: Check GitHub Actions Remaining Minutes

on:
  #schedule:
  #  - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  check-usage:
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub Actions Usage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
        run: |
          # 获取当前月份
          CURRENT_MONTH=$(date +%Y-%m)
          
          echo "查询 $CURRENT_MONTH 的 GitHub Actions 使用情况..."
          
          # 调用GitHub API获取Actions使用情况
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/orgs/$REPO_OWNER/actions/secrets/public-key" || \
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/users/$REPO_OWNER/actions/secrets/public-key")
          
          # 检查是否是组织还是个人
          if echo "$RESPONSE" | grep -q "organization"; then
            TYPE="orgs"
          else
            TYPE="users"
          fi
          
          # 获取使用数据
          USAGE_RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/$TYPE/$REPO_OWNER/actions/usage")
          
          # 提取当前月份的使用分钟数
          MINUTES_USED=$(echo "$USAGE_RESPONSE" | jq -r ".minutes_
          MINused")UTES_INCLUDED=$(echo "$USAGE_RESPONSE" | jq -r ".minutes_included")
          
          # 计算剩余分钟数
          REMAINING_MINUTES=$((MINUTES_INCLUDED - MINUTES_USED))
          
          # 显示结果
          echo "=========================================="
          echo "GitHub Actions 使用情况 ($CURRENT_MONTH):"
          echo "已使用分钟数: $MINUTES_USED"
          echo "包含的免费分钟数: $MINUTES_INCLUDED"
          echo "剩余免费分钟数: $REMAINING_MINUTES"
          echo "=========================================="
          
          # 如果剩余分钟不足10%，发送警告
          if [ $REMAINING_MINUTES -lt $((MINUTES_INCLUDED / 10)) ]; then
            echo "警告: 剩余分钟数不足10%，请注意控制使用量！"
          fi
